version: '2.4'

services:
  laravel-app:
    build:
      context: laravel-app
      args:
        uid: ${UID}
        app: ${COMPOSE_PROJECT_NAME}
        user: ${USER}
    container_name: ${COMPOSE_PROJECT_NAME}_laravel_app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - ../dev/src/${COMPOSE_PROJECT_NAME}:/var/www/${COMPOSE_PROJECT_NAME}
      - ./laravel-app/init-scripts:/tmp/init-scripts
    ports:
      - ${HOST_PORT}:80
    networks:
      - laravel

  # laravel-db:
  #   image: mysql:${MYSQL_VERSION}
  #   container_name: ${COMPOSE_PROJECT_NAME}_laravel_db
  #   volumes:
  #     - ../mysql/${COMPOSE_PROJECT_NAME}:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     - MYSQL_DATABASE=${COMPOSE_PROJECT_NAME}
  #     - MYSQL_USER=${COMPOSE_PROJECT_NAME}
  #     - MYSQL_PASSWORD=${COMPOSE_PROJECT_NAME}
  #   networks:
  #     - laravel

networks:
  laravel:
    name: '${COMPOSE_PROJECT_NAME}'
    driver: bridge