version: '2.4'

services:
  laravel-app:
    build:
      context: laravel-app
      args:
        uid: ${UID}
        app: ${COMPOSE_PROJECT_NAME}
        user: ${USER}
    container_name: ${COMPOSE_PROJECT_NAME}_laravel_app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
      - XDEBUG_CONFIG=remote_host=10.5.0.1
    volumes:
      - ../${COMPOSE_PROJECT_NAME}:/var/www/${COMPOSE_PROJECT_NAME}
      - ./laravel-app/init-scripts:/tmp/init-scripts
    ports:
      - ${HOST_PORT}:80
    networks:
      - laravel

  #mysql-db:
  #  image: mysql:5.7
  #  container_name: mysql-db
  #  volumes:
  #    - ./run/var:/var/lib/mysql
  #  environment:
  #    - MYSQL_ROOT_PASSWORD=root
  #    - MYSQL_DATABASE=db
  #    - MYSQL_USER=user
  #    - MYSQL_PASSWORD=user
  #  networks:
  #    backend:
  #      aliases:
  #        - db

networks:
  laravel:
    name: '${COMPOSE_PROJECT_NAME}'
    driver: bridge